# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
"""Guards on the schema modules vendored in from foamlore.

The generated modules are copied here byte-for-byte from foamlore's
`fode-schemas/`, and foamlore has its own guards comparing the two. Those
guards ask whether the file on disk matches; none of them asks whether the
file is in git. That gap is not hypothetical — `schemas/_laminar_models.py`
sat vendored, correct and untracked while `turbulence_structure.py` imported
it, so every check on both sides passed against a working tree that would
`ImportError` the moment it was cloned.

`test_generated_modules_are_tracked` is therefore the one test here that runs
unconditionally: it needs no foamlore checkout, because "is this file in git"
is a question about this repository alone. The comparison tests need the
sibling and skip without it.

See DEVELOPER.md's "Generated modules (vendored from foamlore)" for the
vendoring procedure itself, which lives on foamlore's side
(`facts/tools/revendor.sh`).
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]

#: The marker every generated module carries in its header. Deriving the list
#: from this rather than naming the modules keeps the guard from going quiet
#: when foamlore adds a family — which it has done three times so far.
BANNER = "GENERATED by foamlore"

#: Vendored alongside the modules and easy to forget, because it is not a
#: `.py` file: it is the licence-attribution record for the OpenFOAM prose the
#: modules quote. It had drifted by 32 lines before foamlore guarded it.
ATTRIBUTION = "THIRD-PARTY.md"


def _generated_modules() -> list[Path]:
    """Every `schemas/*.py` carrying the foamlore banner, by path."""
    return sorted(p for p in (ROOT / "schemas").glob("*.py")
                  if BANNER in p.read_text(encoding="utf-8"))


def _foamlore_root() -> Path | None:
    """The sibling foamlore checkout, or None when there is none.

    Mirrors `fode_emit.fode_root()` on the other side, including its
    asymmetry: an explicitly set FOAMLORE_ROOT that does not exist is a typo
    and raises, while a merely absent sibling is the ordinary case for anyone
    who cloned FoDE alone and skips.
    """
    override = os.environ.get("FOAMLORE_ROOT")
    if override:
        root = Path(override)
        if not root.is_dir():
            raise AssertionError(f"FOAMLORE_ROOT={override} is not a directory")
        return root
    sibling = ROOT.parent / "foamlore"
    return sibling if (sibling / "fode-schemas").is_dir() else None


FOAMLORE = _foamlore_root()
NO_CHECKOUT = (f"no foamlore checkout at {ROOT.parent / 'foamlore'} — "
               "clone it there or set FOAMLORE_ROOT=<checkout>")
needs_foamlore = pytest.mark.skipif(FOAMLORE is None, reason=NO_CHECKOUT)

MODULES = _generated_modules()


def _tracked_paths() -> set[str] | None:
    """Repo-relative paths git knows about, or None outside a git checkout."""
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=ROOT, capture_output=True, text=True,
    )
    if result.returncode != 0:
        return None
    return {p for p in result.stdout.split("\0") if p}


def test_some_generated_modules_are_present():
    """The list is derived, so an empty one would silently pass everything."""
    assert MODULES, (
        f"no module under schemas/ carries the {BANNER!r} banner — either the "
        "vendored modules are gone or the banner text changed, and every "
        "other guard in this file is now vacuous")


def test_generated_modules_are_tracked():
    """A vendored module must be in git, not merely on disk.

    This is the check the cross-repo guards structurally cannot make. foamlore
    compares its `fode-schemas/` against this working tree; a file present
    here but absent from the index is byte-identical and therefore passes,
    while a fresh clone of this repository does not contain it at all.

    Vendoring is a copy, and a copy leaves an untracked file. `revendor.sh`
    reports what it moved with `git diff --stat`, which does not list
    untracked paths, so nothing between the generator and the commit says
    "git add" out loud. This does.
    """
    tracked = _tracked_paths()
    if tracked is None:
        pytest.skip("not a git checkout")

    untracked = [str(p.relative_to(ROOT)) for p in MODULES
                 if str(p.relative_to(ROOT)) not in tracked]
    assert not untracked, (
        "vendored schema module(s) present on disk but not in git — a fresh "
        "clone would not have them, and anything importing them would fail:\n"
        + "\n".join(f"  {p}" for p in untracked)
        + "\n\nStage them by name:\n  git add "
        + " ".join(untracked))


@needs_foamlore
@pytest.mark.parametrize("path", MODULES, ids=lambda p: p.name)
def test_vendored_module_matches_foamlore(path):
    """The copy here is still the one foamlore generated."""
    assert FOAMLORE is not None
    theirs = FOAMLORE / "fode-schemas" / path.name
    assert theirs.is_file(), (
        f"{path.name} carries the generated banner but foamlore has no "
        f"{theirs} — it was either hand-written here or removed there")
    assert path.read_bytes() == theirs.read_bytes(), (
        f"schemas/{path.name} differs from foamlore's copy. Do not edit it "
        "here; re-vendor with foamlore's facts/tools/revendor.sh")


@needs_foamlore
def test_every_foamlore_module_is_vendored():
    """A module foamlore generates but nobody copied over.

    The opposite direction from the test above, and the one that cannot be
    seen from this side without the sibling: a new generated family is simply
    absent here, so there is no file to compare and no banner to find.
    """
    assert FOAMLORE is not None
    ours = {p.name for p in MODULES}
    theirs = {p.name for p in (FOAMLORE / "fode-schemas").glob("*.py")}
    missing = sorted(theirs - ours)
    assert not missing, (
        "foamlore generates module(s) that are not vendored here:\n"
        + "\n".join(f"  {name}" for name in missing)
        + "\n\nRun foamlore's facts/tools/revendor.sh, then git add them.")


@needs_foamlore
def test_vendored_attribution_matches():
    """THIRD-PARTY.md is vendored too, and is not a `.py` file.

    It records which OpenFOAM copyright holders the quoted prose belongs to,
    so drift here under-credits upstream rather than merely going stale.
    """
    assert FOAMLORE is not None
    ours = ROOT / ATTRIBUTION
    theirs = FOAMLORE / ATTRIBUTION
    assert ours.is_file(), f"{ATTRIBUTION} is missing from this checkout"
    assert theirs.is_file(), f"{ATTRIBUTION} is missing from {FOAMLORE}"
    assert ours.read_bytes() == theirs.read_bytes(), (
        f"{ATTRIBUTION} differs from foamlore's copy — re-vendor it with the "
        "schema modules; foamlore's revendor.sh ships both.")
