# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
"""Tests for the foamlore-generated turbulence-model schema modules.

schemas/turbulence_properties.py and schemas/momentum_transport.py are
vendored from the foamlore repository (facts/tools/generate_fode_schemas.py)
and must never be edited by hand — regenerate them there instead.
"""
from pathlib import Path

import pytest

from schemas import momentum_transport, turbulence_properties
from schemas._base import (
    FOUNDATION_V7,
    FOUNDATION_V13,
    OPENCFD_V2512,
    OPENCFD_V2606,
    ChoiceItem,
    KeySchema,
)
from schemas.builtin import get_default_schema_config
from schemas.registry import SchemaRegistry

# ── fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture
def config_path(monkeypatch, tmp_path):
    path = tmp_path / "schema_config.json"
    monkeypatch.setattr("schemas.config_store.CONFIG_FILE", path)
    return path


@pytest.fixture
def registry(config_path):
    return SchemaRegistry()


# ── module shape ──────────────────────────────────────────────────────────────

class TestModuleShape:
    @pytest.mark.parametrize(
        "module,target",
        [
            (turbulence_properties, "turbulenceProperties"),
            (momentum_transport, "momentumTransport"),
        ],
    )
    def test_target_file_and_types(self, module, target):
        assert module.TARGET_FILE == target
        assert isinstance(module.SCHEMAS, dict)
        assert module.SCHEMAS
        for key, schema in module.SCHEMAS.items():
            assert isinstance(schema, KeySchema), key
            for choice in schema.choices:
                assert isinstance(choice, ChoiceItem), key

    def test_registered_by_default(self):
        modules = get_default_schema_config()["schema_modules"]
        assert "schemas.turbulence_properties" in modules
        assert "schemas.momentum_transport" in modules

    @pytest.mark.parametrize(
        "name", ["turbulence_properties", "momentum_transport"]
    )
    def test_generated_banner_present(self, name):
        # Guard against hand edits: the vendored files must keep the
        # foamlore GENERATED header.
        text = (Path("schemas") / f"{name}.py").read_text(encoding="utf-8")
        assert "GENERATED by foamlore" in text
        assert "NEVER edit by hand" in text


# ── registry lookup ───────────────────────────────────────────────────────────

class TestRegistryLookup:
    def test_qualified_coefficient(self, registry):
        schema = registry.schema_for_file_key(
            "constant/turbulenceProperties", "beta1", parent_key="kOmegaSSTCoeffs"
        )
        assert schema is not None
        assert schema.key == "beta1"
        assert OPENCFD_V2512 in schema.supported_in
        assert FOUNDATION_V7 in schema.supported_in
        assert any(c.value == "0.075" for c in schema.choices)

    def test_plain_fallback_in_ras_dict(self, registry):
        # coefficient placed directly in the RAS dict (optionalSubDict idiom)
        schema = registry.schema_for_file_key(
            "constant/turbulenceProperties", "Cmu", parent_key="RAS"
        )
        assert schema is not None
        assert any(c.value == "0.09" for c in schema.choices)

    def test_momentum_transport_lookup(self, registry):
        schema = registry.schema_for_file_key(
            "constant/momentumTransport", "sigmaNut", parent_key="SpalartAllmarasCoeffs"
        )
        assert schema is not None
        assert schema.supported_in == (FOUNDATION_V13,)

    def test_version_specific_coefficient(self, registry):
        schema = registry.schema_for_file_key(
            "constant/turbulenceProperties", "decayControl", parent_key="kOmegaSSTCoeffs"
        )
        assert schema is not None
        assert schema.supported_in == (OPENCFD_V2512, OPENCFD_V2606)
        assert "Only present in" in schema.note

    def test_coeffs_dict_entry(self, registry):
        schema = registry.schema_for_file_key(
            "constant/turbulenceProperties", "kEpsilonCoeffs", parent_key="RAS"
        )
        assert schema is not None
        assert "kEpsilon" in schema.description

    def test_no_leak_into_other_files(self, registry):
        assert (
            registry.schema_for_file_key("system/controlDict", "beta1", parent_key="RAS")
            is None
        )
