# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025-2026 Shinji NAKAGAWA
"""Type-checking-only stand-in for the full ``MainWindow``.

Every ``ui/mixins/_*.py`` module defines a *mixin*: a plain class with no
common base, meant to be combined with the other twelve mixins and
``QMainWindow`` into the real ``MainWindow`` (see ``ui/main_window.py``). At
runtime that composition is exactly what makes ``self.tree``,
``self.state``, ``self._load_tree(...)`` and so on resolve correctly from
inside any one mixin's methods — but mypy checks each mixin module on its
own, where a plain ``class _FileOpsMixin:`` has no idea that ``self`` will
ever have a ``.tree`` or a ``._load_tree()``.

``MainWindowProtocol`` documents that combined surface for mypy's benefit
only. Every ``ui/mixins/_*.py`` module does::

    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        from ui.mixins._protocol import MainWindowProtocol as _Base
    else:
        _Base = object

    class _FileOpsMixin(_Base):
        ...

so ``_Base`` is ``MainWindowProtocol`` while mypy is looking (giving every
method in the file the full attribute/method surface below) and plain
``object`` at runtime (an entirely inert base — the class's runtime MRO,
and therefore ``MainWindow``'s own MRO once all thirteen mixins are combined
with it, is unchanged).

This module must not import ``ui.main_window`` or any ``ui.mixins.*``
module: doing so would make the mixins' ``TYPE_CHECKING`` base inherit from
a class that (for real, at runtime) inherits from the mixins themselves —
a genuine inheritance cycle, not just a circular *import*, which mypy
rejects outright. Inheriting ``QMainWindow`` here directly is what a real
``MainWindow`` does too; it is not a shortcut around that rule, since this
class and ``MainWindow`` are otherwise unrelated as far as mypy is concerned.

Keep this file's method list in sync with the mixins' own signatures — mypy
treats it as a real base class during type checking, so a mismatched stub
signature here surfaces as a spurious "incompatible with supertype" error
on the mixin's real method.
"""
from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QFileSystemWatcher, QModelIndex, QSortFilterProxyModel, QTimer
from PySide6.QtGui import QAction
from PySide6.QtWidgets import (
    QCheckBox,
    QFrame,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMenu,
    QPushButton,
    QSplitter,
    QTabWidget,
    QTreeView,
)

from foam.include_resolver import ResolvedInclude
from foam.nodes import FoamNode
from foam.parser import OpenFoamParser
from ui.app_state import AppState, UndoSnapshot
from ui.dialogs.find_examples_dialog import FindExamplesDialog
from ui.dialogs.log_summary_dialog import LogSummaryDialog
from ui.pane_minimize import PaneMinimizer
from ui.panels.block_mesh_panel import BlockMeshPanel
from ui.panels.boundary_view_panel import BoundaryViewPanel
from ui.panels.comparison_tree_panel import ComparisonTreePanel
from ui.panels.detail_panel import DetailPanel
from ui.panels.editor_panel import EditorPanel
from ui.panels.file_list_panel import FileListPanel
from ui.panels.terminal_panel import TerminalPanel


class MainWindowProtocol(QMainWindow):
    # ── shared state ──────────────────────────────────────────────────────────
    state: AppState

    # ── widgets / panels built by MainWindow._build_ui() and friends ──────────
    file_list_panel: FileListPanel
    comparison_panel: ComparisonTreePanel
    detail_panel: DetailPanel
    editor_panel: EditorPanel
    boundary_panel: BoundaryViewPanel
    terminal_panel: TerminalPanel | None
    block_mesh_panel: BlockMeshPanel | None
    tree: QTreeView
    proxy_model: QSortFilterProxyModel
    tree_filter_input: QLineEdit
    editor_autoscroll_checkbox: QCheckBox
    current_case_label: QLabel
    current_file_label: QLabel
    bottom_tabs: QTabWidget
    upper_tabs: QTabWidget
    main_splitter: QSplitter
    right_splitter: QSplitter
    right_upper_splitter: QSplitter | None
    _tree_bm_splitter: QSplitter
    _bm_side_by_side_btn: QPushButton | None
    _bottom_minimize_btn: QPushButton
    # Minimizable panes, by the ui/pane_minimize.py PANE_* names.
    _pane_minimizers: dict[str, PaneMinimizer]
    _pane_actions: dict[str, QAction]
    _detail_auto_minimized: bool
    _diff_bar: QFrame
    _diff_path_label: QLabel
    _side_by_side_cb: QCheckBox
    _case_dir_watcher: QFileSystemWatcher
    _foam_monitor_timer: QTimer
    _file_list_refresh_timer: QTimer
    _log_summary_dialog: LogSummaryDialog | None
    _find_examples_dialog: FindExamplesDialog | None

    # ── Tools/View-menu actions (None until _build_menu_bar() runs) ───────────
    _find_examples_action: QAction
    _show_type_action: QAction
    _restore_session_action: QAction
    _forget_session_action: QAction
    _blockmesh_action: QAction | None
    _foam_monitor_action: QAction | None
    _restore_0dir_action: QAction | None
    _run_blockmesh_action: QAction | None
    _run_snappyhexmesh_action: QAction | None
    _run_topo_set_action: QAction | None
    _run_setfields_action: QAction | None
    _run_checkmesh_action: QAction | None
    _run_allrun_action: QAction | None
    _run_allclean_action: QAction | None
    _clean_case_action: QAction | None
    _open_paraview_action: QAction | None
    _view_log_summary_action: QAction | None

    # ── from _BoundaryOpsMixin (ui/mixins/_boundary_ops.py) ───────────────────
    def _available_field_dirs(self) -> list[str]:
        raise NotImplementedError
    def _reload_boundary_panel(self) -> None: ...
    def _on_patch_edit_requested(self, path: str, patch_name: str, patch_node: object) -> None: ...
    def _on_patch_create_requested(self, path: str, patch_name: str) -> None: ...
    def _on_patch_paste_requested(self, path: str, patch_name: str, content: str) -> None: ...
    def _on_patch_delete_requested(self, path: str, patch_name: str) -> None: ...
    def _on_rename_boundary_by_name(self, old_name: str) -> None: ...
    def _on_patch_selected(self, path: str, patch_name: str) -> None: ...
    def _apply_boundary_root_change(self, path: str, root: FoamNode) -> None: ...
    def _on_patch_delete_all_requested(self, patch_name: str) -> None: ...
    def _on_patch_add_all_requested(self, patch_name: str) -> None: ...

    # ── from _CaseOpsMixin (ui/mixins/_case_ops.py) ───────────────────────────
    def open_case(self) -> None: ...
    def reload_case(self) -> None: ...
    def open_from_library(self) -> None: ...
    def duplicate_case(self) -> None: ...
    def duplicate_from_library(self) -> None: ...
    def _duplicate_case_from(self, source: str, fallback_dest_parent: str | None = None) -> None: ...
    def _pick_case_from_library(self, title: str) -> str | None: ...
    def _confirm_and_remove_existing_dir(self, dest: Path, error_title: str) -> bool:
        raise NotImplementedError
    def _run_duplicate(self, source_dir: str, dest: Path, copy_all: bool) -> None: ...
    def save_as_new_case(self) -> None: ...
    def _confirm_open_dir(self, directory: str) -> bool:
        raise NotImplementedError
    def _copy_visible_files(self, source_dir: str, dest: Path) -> None: ...
    def set_default_case_directory(self) -> None: ...
    def manage_case_library(self) -> None: ...
    def reset_window_size(self) -> None: ...
    def reset_all_settings(self) -> None: ...

    # ── from _DiffOpsMixin (ui/mixins/_diff_ops.py) ───────────────────────────
    def _on_side_by_side_toggled(self, checked: bool) -> None: ...
    def _compare_with_case(self) -> None: ...
    def _start_comparison_with(self, directory: str) -> None: ...
    def _reset_diff_for_case_dir(self, directory: str, previous_dir: str | None) -> None: ...
    def _clear_diff(self) -> None: ...
    def _recompute_diff(self) -> None: ...
    def _precompute_all_diff_counts(self) -> None: ...
    def _precompute_diff_step(
        self, paths: list, idx: int, case_path: Path, diff_path: Path, failures: int = 0
    ) -> None: ...

    # ── from _FileManagementOpsMixin (ui/mixins/_file_mgmt_ops.py) ────────────
    def _on_create_file_requested(self, case_dir: str, group: str) -> None: ...
    def _on_add_file_requested(self, case_dir: str, group: str) -> None: ...
    def _create_backup(self, path: str) -> bool:
        raise NotImplementedError
    def _on_backup_file_requested(self, path: str) -> None: ...
    def _on_manage_extra_files(self) -> None: ...
    def _on_remove_extra_file(self, abs_path: str) -> None: ...
    def _on_delete_file_requested(self, path: str) -> None: ...
    def _on_duplicate_file_requested(self, path: str) -> None: ...
    def _on_copy_into_case_requested(self, src_path: str) -> None: ...
    def _resolved_include_for(self, target_path: str) -> ResolvedInclude | None: ...
    def _read_only_refused(self, path: str) -> bool:
        raise NotImplementedError
    def _on_duplicate_dir_requested(self, case_dir: str, src: str, dst: str) -> None: ...
    def _on_delete_dir_requested(self, case_dir: str, group: str) -> None: ...
    def _on_clean_backups(self) -> None: ...

    # ── from _FileOpsMixin (ui/mixins/_file_ops.py) ───────────────────────────
    def _load_case_dir(self, directory: str) -> None: ...
    def _reload_file_list(self) -> None: ...
    def _on_case_dir_changed_on_disk(self, path: str) -> None: ...
    def _parse_and_update(self, path: str, text: str) -> OpenFoamParser:
        raise NotImplementedError
    def load_selected_file(self, path: str) -> None: ...
    def save_file(self) -> None: ...
    def save_all_files(self) -> None: ...
    def reset_file_list(self) -> None: ...
    def _on_add_time_dir(self, dir_name: str) -> None: ...
    def _on_remove_extra_dir(self, rel_dir: str) -> None: ...
    def _purge_file_caches(self, path: str) -> None: ...
    def _is_auto_scan_group(self, group: str) -> bool:
        raise NotImplementedError
    def _case_file_paths(
        self, case_dir: str
    ) -> tuple[list[str], list[str] | None, list[str] | None, dict[str, str]]:
        raise NotImplementedError
    def _open_included_target(self, directive_text: str) -> None: ...
    def _include_notes_for(self, path: str) -> dict[str, str]:
        raise NotImplementedError

    # ── from _FoamMonitorOpsMixin (ui/mixins/_foam_monitor_ops.py) ────────────
    def _on_foam_monitor_clicked(self) -> None: ...
    def _stop_foam_monitor(self) -> None: ...
    def _on_foam_monitor_poll(self) -> None: ...
    def _update_foam_monitor_btn(self) -> None: ...

    # ── from _ModelOpsMixin (ui/mixins/_model_ops.py) ─────────────────────────
    def _save_current_buffer(self) -> None: ...
    def _after_model_edit(self) -> None: ...
    def _update_viewer_panels(self, path: str, root: FoamNode) -> None: ...
    def _on_tree_data_changed(self, top_left, bottom_right, roles) -> None: ...
    def _load_tree(self, root: FoamNode) -> None: ...
    def _clear_current_file(self) -> None: ...
    def _write_root_to_buffer(self, path: str, root: FoamNode) -> str:
        raise NotImplementedError
    def _cache_parsed_root(self, path: str) -> FoamNode | None: ...
    def _is_read_only(self, path: str | None) -> bool:
        raise NotImplementedError
    def _mark_dirty(self) -> None: ...
    def _mark_path_dirty(self, path: str) -> None: ...
    def _confirm_discard_if_needed(self) -> bool:
        raise NotImplementedError

    # ── from _PanelOpsMixin (ui/mixins/_panel_ops.py) ─────────────────────────
    def _on_toggle_blockmesh_panel(self, checked: bool) -> None: ...
    def _on_toggle_bm_side_by_side(self, checked: bool) -> None: ...
    def _update_bm_side_by_side_btn(self) -> None: ...
    def _on_terminal_mode_changed(self, use_xterm: bool) -> None: ...
    def _build_pane_menu_actions(self, view_menu: QMenu) -> None: ...
    def set_pane_minimized(self, name: str, minimized: bool) -> None: ...
    def toggle_pane_minimized(self, name: str) -> None: ...
    def _on_pane_action_toggled(self, name: str, checked: bool) -> None: ...
    def _on_toggle_bottom_pane_btn(self) -> None: ...
    def _on_splitter_handle_double_click(self, splitter: QSplitter, index: int) -> None: ...
    def _auto_minimize_detail_for_side_by_side(self, side_by_side: bool) -> None: ...
    def _update_pane_minimize_controls(self) -> None: ...

    # ── from _ToolsOpsMixin (ui/mixins/_tools_ops.py) ─────────────────────────
    def _run_in_terminal(self, cmd: str) -> None: ...
    def _rerun_over_results_warning(self, sentence: str) -> str:
        raise NotImplementedError
    def _run_tool_with_options(
        self, tool: str, warning_text: str = "", prefix_option: tuple[str, str, bool] | None = None
    ) -> None: ...
    def _on_restore_0dir_clicked(self) -> None: ...
    def _on_run_blockmesh_clicked(self) -> None: ...
    def _on_run_snappyhexmesh_clicked(self) -> None: ...
    def _on_run_topo_set_clicked(self) -> None: ...
    def _on_run_setfields_clicked(self) -> None: ...
    def _on_run_checkmesh_clicked(self) -> None: ...
    def _on_run_allrun_clicked(self) -> None: ...
    def _on_run_allclean_clicked(self) -> None: ...
    def _on_clean_case_clicked(self) -> None: ...
    def _show_cached_dialog(self, attr: str, factory) -> None: ...
    def _on_view_log_summary_clicked(self) -> None: ...
    def _on_find_examples_clicked(self) -> None: ...
    def _on_example_compare_requested(self, case_dir: str) -> None: ...
    def _on_example_duplicate_requested(self, case_dir: str) -> None: ...
    def _on_open_paraview_clicked(self) -> None: ...
    def _update_tools_actions(self) -> None: ...

    # ── from _TreeCrudOpsMixin (ui/mixins/_tree_crud_ops.py) ──────────────────
    def _setup_tree_copy_paste(self) -> None: ...
    def _resolve_tree_include(self, node: FoamNode) -> ResolvedInclude | None: ...
    def _on_tree_double_clicked(self, index) -> None: ...
    def _on_tree_context_menu(self, pos) -> None: ...
    def _tree_copy_value(self) -> None: ...
    def _tree_paste_value(self) -> None: ...
    def _tree_add_entry_after(self, node: FoamNode) -> None: ...
    def _edit_first_editable_column(self, index) -> None: ...
    def _tree_add_child_entry(self, node: FoamNode) -> None: ...
    def _tree_duplicate(self, node: FoamNode) -> None: ...
    def _tree_comment_out(self, node: FoamNode) -> None: ...
    def _tree_delete(self, node: FoamNode) -> None: ...
    def _tree_restore_comment(self, node: FoamNode) -> None: ...
    def _apply_comparison_value(self, b_node: FoamNode) -> None: ...
    def _node_indent(self, node: FoamNode) -> int:
        raise NotImplementedError
    def _mark_parent_modified(self, parent_node: FoamNode) -> None: ...
    def _is_commented_out_node(self, node: FoamNode) -> bool:
        raise NotImplementedError

    # ── from _TreeSyncOpsMixin (ui/mixins/_tree_sync_ops.py) ──────────────────
    def _sync_tree_to_editor_line(self) -> None: ...
    def _find_deepest(self, node: FoamNode, line: int) -> FoamNode | None: ...
    def on_tree_selection(self) -> None: ...
    def _highlight_selected_block(self, node: FoamNode, row: int) -> None: ...
    def _on_value_apply(self, new_value: str) -> None: ...
    def _on_field_value_apply(self, field_type: str, raw_value: str) -> None: ...
    def apply_text_to_tree(self) -> None: ...
    def reload_text_from_tree(self) -> None: ...
    def _on_blockmesh_vertices_changed(self, idx: int, xyz: list) -> None: ...
    def _on_user_text_changed(self) -> None: ...

    # ── from _UiOpsMixin (ui/mixins/_ui_ops.py) ───────────────────────────────
    def _confirm(self, title: str, message: str) -> bool:
        raise NotImplementedError
    def _build_radio_menu(self, parent_menu, title, options, current, slot) -> None: ...
    def _build_language_menu(self, parent_menu) -> None: ...
    def _on_language_changed(self, action: QAction) -> None: ...
    def _build_appearance_menu(self, parent_menu) -> None: ...
    def _on_theme_changed(self, action: QAction) -> None: ...
    def _build_ui_scale_menu(self, parent_menu) -> None: ...
    def _on_ui_scale_changed(self, action: QAction) -> None: ...
    def _on_restore_session_toggled(self, enabled: bool) -> None: ...
    def _refresh_forget_session_action(self) -> None: ...
    def _forget_saved_session(self) -> None: ...
    def open_schema_manager(self) -> None: ...
    def generate_foam_keywords(self) -> None: ...
    def show_about(self) -> None: ...
    def show_keyboard_shortcuts(self) -> None: ...
    def show_openfoam_resources(self) -> None: ...
    def _connect_tree_selection(self) -> None: ...
    def _current_primary_index(self) -> QModelIndex:
        raise NotImplementedError
    def _to_source(self, proxy_index: QModelIndex) -> QModelIndex:
        raise NotImplementedError
    def _to_proxy(self, source_index: QModelIndex) -> QModelIndex:
        raise NotImplementedError
    def _on_toggle_type_column(self, checked: bool) -> None: ...
    def _resize_tree_columns(self) -> None: ...
    def _collapse_foam_file(self) -> None: ...
    def _update_case_label(self) -> None: ...
    def _update_file_label(self) -> None: ...
    def _update_window_title(self) -> None: ...
    def _update_sync_checkbox(self) -> None: ...

    # ── from _UndoOpsMixin (ui/mixins/_undo_ops.py) ───────────────────────────
    def _setup_tree_undo(self) -> None: ...
    def _on_model_about_to_change(self) -> None: ...
    def _commit_pending_undo(self) -> None: ...
    def _checkpoint_for_undo(self, paths: list[str] | None = None) -> None: ...
    def _end_undo_op(self) -> None: ...
    def _trim_undo_stack(self) -> None: ...
    def _undo_snapshot_of(self, paths: list[str]) -> UndoSnapshot | None: ...
    def _undo_text_for(self, path: str) -> str | None: ...
    def _clear_undo_stacks(self) -> None: ...
    def _tree_undo(self) -> None: ...
    def _tree_redo(self) -> None: ...
    def _undo_redo_step(
        self,
        from_stack: list[UndoSnapshot],
        to_stack: list[UndoSnapshot],
        empty_msg: str,
        done_msg: str,
    ) -> None: ...
    def _restore_undo_snapshot(self, snap: UndoSnapshot) -> None: ...
    def _restored_dirty(self, path: str, text: str, snap_dirty: bool) -> bool:
        raise NotImplementedError
