# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_fode_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: DeltaOmegaTilde.derived.json, IDDESDelta.derived.json, Prandtl.derived.json,
#   SLADelta.derived.json, cubeRootVol.derived.json, maxDeltaxyz.derived.json,
#   maxDeltaxyzCubeRoot.derived.json, smooth.derived.json, vanDriest.derived.json
# Source commits: opencfd-v2212=6690815, opencfd-v2306=a6e826b, opencfd-v2312=1d8f0d5,
#   opencfd-v2406=630d60d, opencfd-v2412=d394908, opencfd-v2506=615aae6, opencfd-v2512=87ed40d,
#   opencfd-v2606=481094f, foundation-7=6334942, foundation-8=a86b07b, foundation-9=d87800e,
#   foundation-10=89f925d, foundation-11=9cbf94f, foundation-12=0b487fc, foundation-13=17489db,
#   foundation-14=c046c72, opencfd-v2106=c15bfde, opencfd-v2112=14aeaf8, opencfd-v2206=76d719d
from __future__ import annotations

# model -> (upstream description, upstream note), quoted from
# each model's own header. Prose only: the laminar coefficient
# keys are hand-owned by schemas/turbulence_structure.py and a
# generated module loads second, so emitting them here would
# silently replace what FoDE measured.
MODEL_DOCS: dict[str, tuple[str, str]] = {
    "DeltaOmegaTilde": (
        (
            "Delta formulation that accounts for the orientation of the vorticity "
            "vector. In \"2D-regions\" (i.e. xy-plane), delta is of the order "
            "max(delta_x,delta_y), so that the influence of delta_z is discarded. This "
            "can help to accelerate the transition from RANS to LES in hybrid RANS/LES "
            "simulations."
        ),
        (
            "Reference: Shur, M. L., Spalart, P. R., Strelets, M. K., & Travin, A. K. "
            "(2015). An enhanced version of DES with rapid transition from RANS to LES "
            "in separated flows. Flow, turbulence and combustion, 95(4), 709-737. "
            "DOI:10.1007/s10494-015-9618-0"
        ),
    ),
    "IDDESDelta": (
        (
            "IDDESDelta used by the IDDES (improved low Re Spalart-Allmaras DES model) "
            "The min and max delta are calculated using the face to face distance of "
            "the cell."
        ),
        "",
    ),
    "Prandtl": (
        (
            "Apply Prandtl mixing-length based damping function to the specified "
            "geometric delta to improve near-wall behavior or LES models."
        ),
        "",
    ),
    "SLADelta": (
        (
            "Delta formulation that accounts for the orientation of the vorticity "
            "vector and a flow-sensitised function to detect 2D flow regions. Delta "
            "value is strongly reduced in these regions to accelerate the transition "
            "from RANS to LES in hybrid RANS/LES simulations."
        ),
        (
            "Reference: Shur, M. L., Spalart, P. R., Strelets, M. K., & Travin, A. K. "
            "(2015). An enhanced version of DES with rapid transition from RANS to LES "
            "in separated flows. Flow, turbulence and combustion, 95(4), 709-737. "
            "DOI:10.1007/s10494-015-9618-0"
        ),
    ),
    "cubeRootVol": (
        "Simple cube-root of cell volume delta used in LES models.",
        "",
    ),
    "maxDeltaxyz": (
        (
            "Delta calculated by taking the maximum distance between the cell centre "
            "and any face centre. For a regular hex cell, the computed delta will "
            "equate to half of the cell width; accordingly, the deltaCoeff model "
            "coefficient should be set to 2 for this case."
        ),
        "",
    ),
    "maxDeltaxyzCubeRoot": (
        "Maximum delta between maxDeltaxyz and cubeRootVolDelta.",
        "",
    ),
    "smooth": (
        (
            "Smoothed delta which takes a given simple geometric delta and applies "
            "smoothing to it such that the ratio of deltas between two cells is no "
            "larger than a specified amount, typically 1.15."
        ),
        "",
    ),
    "vanDriest": (
        "Simple cube-root of cell volume delta used in incompressible LES models.",
        "",
    ),
}
