# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_fode_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: Giesekus.derived.json, Maxwell.derived.json, PTT.derived.json, Stokes.derived.json,
#   generalisedNewtonian.derived.json, generalizedNewtonian.derived.json,
#   lambdaThixotropic.derived.json
# Source commits: foundation-7=6334942, foundation-8=a86b07b, foundation-9=d87800e,
#   foundation-10=89f925d, foundation-11=9cbf94f, foundation-12=0b487fc, foundation-13=17489db,
#   foundation-14=c046c72, opencfd-v2106=c15bfde, opencfd-v2112=14aeaf8, opencfd-v2206=76d719d,
#   opencfd-v2212=6690815, opencfd-v2306=a6e826b, opencfd-v2312=1d8f0d5, opencfd-v2406=630d60d,
#   opencfd-v2412=d394908, opencfd-v2506=615aae6, opencfd-v2512=87ed40d, opencfd-v2606=481094f
from __future__ import annotations

# model -> (upstream description, upstream note), quoted from
# each model's own header. Prose only: the laminar coefficient
# keys are hand-owned by schemas/turbulence_structure.py and a
# generated module loads second, so emitting them here would
# silently replace what FoDE measured.
MODEL_DOCS: dict[str, tuple[str, str]] = {
    "Giesekus": (
        (
            "Giesekus model for viscoelasticity using the upper-convected time "
            "derivative of the stress tensor with support for multiple modes."
        ),
        (
            "Reference: Giesekus, H., 1982. A simple constitutive equation for polymer "
            "fluids based on the concept of deformation-dependent tensional mobility. "
            "J. Non-Newton. Fluid. 11, 69–109."
        ),
    ),
    "Maxwell": (
        (
            "Maxwell model for viscoelasticity using the upper-convected time "
            "derivative of the stress tensor. See "
            "http://en.wikipedia.org/wiki/Upper-convected_Maxwell_model"
        ),
        (
            "Reference: Amoreira, L. J., & Oliveira, P. J. (2010). Comparison of "
            "different formulations for the numerical calculation of unsteady "
            "incompressible viscoelastic fluid flow. Adv. Appl. Math. Mech, 4, "
            "483-502. DOI:10.4208/aamm.10-m1010"
        ),
    ),
    "PTT": (
        (
            "PTT model for viscoelasticity using the upper-convected time derivative "
            "of the stress tensor with support for multiple modes."
        ),
        (
            "Reference: Phan-Thien, N., & Tanner, R. I. (1977). A new constitutive "
            "equation derived from network theory. Journal of Non-Newtonian Fluid "
            "Mechanics, 2(4), 353-365."
        ),
    ),
    "Stokes": (
        "Turbulence model for Stokes flow.",
        "",
    ),
    "generalisedNewtonian": (
        "Momentum transport model for shear-dependent Non-Newtonian flow.",
        "",
    ),
    "generalizedNewtonian": (
        "Turbulence model for shear-dependent Non-Newtonian flow.",
        "",
    ),
    "lambdaThixotropic": (
        (
            "Thixotropic viscosity momentum transport model based on the evolution of "
            "the structural parameter \\f$ \\lambda \\f$:"
        ),
        (
            "Reference: Barnes H A, 1997. Thixotropy - a review. J. Non-Newtonian "
            "Fluid Mech 70, pp 1-33"
        ),
    ),
}
