# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_transport_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: Arrhenius.derived.json, BirdCarreau.derived.json, Casson.derived.json,
#   CrossPowerLaw.derived.json, HerschelBulkley.derived.json, Newtonian.derived.json,
#   constant.derived.json, powerLaw.derived.json, strainRateFunction.derived.json
# Source commits: opencfd-v2106=c15bfde, opencfd-v2112=14aeaf8, opencfd-v2206=76d719d,
#   opencfd-v2212=6690815, opencfd-v2306=a6e826b, opencfd-v2312=1d8f0d5, opencfd-v2406=630d60d,
#   opencfd-v2412=d394908, opencfd-v2506=615aae6, opencfd-v2512=87ed40d, opencfd-v2606=481094f,
#   foundation-7=6334942, foundation-8=a86b07b, foundation-9=d87800e, foundation-10=89f925d,
#   foundation-11=9cbf94f, foundation-12=0b487fc, foundation-13=17489db, foundation-14=c046c72
from __future__ import annotations

from schemas._base import (
    FOUNDATION_SERIES,
    FOUNDATION_V7,
    FOUNDATION_V7_V9,
    FOUNDATION_V8,
    FOUNDATION_V9,
    FOUNDATION_V10,
    FOUNDATION_V10_V14,
    FOUNDATION_V11,
    FOUNDATION_V12,
    FOUNDATION_V13,
    FOUNDATION_V14,
    OPENCFD_SERIES,
    OPENCFD_V2106,
    OPENCFD_V2106_V2212,
    OPENCFD_V2112,
    OPENCFD_V2206,
    OPENCFD_V2212,
    OPENCFD_V2306,
    OPENCFD_V2312,
    OPENCFD_V2406,
    OPENCFD_V2412,
    OPENCFD_V2506,
    OPENCFD_V2512,
    OPENCFD_V2606,
    ChoiceItem,
    KeySchema,
)

TARGET_FILES = ("transportProperties", "physicalProperties")

_TARGET_CHECKOUTS = {
    "transportProperties": (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
        "foundation-7",
        "foundation-8",
        "foundation-9",
    ),
    "physicalProperties": (
        "foundation-10",
        "foundation-11",
        "foundation-12",
        "foundation-13",
        "foundation-14",
    ),
}


# Canonical release order, oldest first per fork.
_ORDER = (
    "foundation-7",
    "foundation-8",
    "foundation-9",
    "foundation-10",
    "foundation-11",
    "foundation-12",
    "foundation-13",
    "foundation-14",
    "opencfd-v2106",
    "opencfd-v2112",
    "opencfd-v2206",
    "opencfd-v2212",
    "opencfd-v2306",
    "opencfd-v2312",
    "opencfd-v2406",
    "opencfd-v2412",
    "opencfd-v2506",
    "opencfd-v2512",
    "opencfd-v2606",
)

_RELEASE = {
    "foundation-7": (FOUNDATION_V7, "Foundation v7"),
    "foundation-8": (FOUNDATION_V8, "Foundation v8"),
    "foundation-9": (FOUNDATION_V9, "Foundation v9"),
    "foundation-10": (FOUNDATION_V10, "Foundation v10"),
    "foundation-11": (FOUNDATION_V11, "Foundation v11"),
    "foundation-12": (FOUNDATION_V12, "Foundation v12"),
    "foundation-13": (FOUNDATION_V13, "Foundation v13"),
    "foundation-14": (FOUNDATION_V14, "Foundation v14"),
    "opencfd-v2106": (OPENCFD_V2106, "OpenCFD v2106"),
    "opencfd-v2112": (OPENCFD_V2112, "OpenCFD v2112"),
    "opencfd-v2206": (OPENCFD_V2206, "OpenCFD v2206"),
    "opencfd-v2212": (OPENCFD_V2212, "OpenCFD v2212"),
    "opencfd-v2306": (OPENCFD_V2306, "OpenCFD v2306"),
    "opencfd-v2312": (OPENCFD_V2312, "OpenCFD v2312"),
    "opencfd-v2406": (OPENCFD_V2406, "OpenCFD v2406"),
    "opencfd-v2412": (OPENCFD_V2412, "OpenCFD v2412"),
    "opencfd-v2506": (OPENCFD_V2506, "OpenCFD v2506"),
    "opencfd-v2512": (OPENCFD_V2512, "OpenCFD v2512"),
    "opencfd-v2606": (OPENCFD_V2606, "OpenCFD v2606"),
}

# Checkout set -> (supported_in constants, human text).
_TAGS = {
    (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "foundation-10",
        "foundation-11",
        "foundation-12",
        "foundation-13",
        "foundation-14",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ):
        ((FOUNDATION_SERIES, OPENCFD_SERIES), "Foundation v7-v14, OpenCFD v2106-v2606"),
    (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
    ):
        ((FOUNDATION_V7_V9, OPENCFD_V2106_V2212), "Foundation v7-v9, OpenCFD v2106-v2212"),
    (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ):
        ((FOUNDATION_V7_V9, OPENCFD_SERIES), "Foundation v7-v9, OpenCFD v2106-v2606"),
    (
        "foundation-10",
        "foundation-11",
        "foundation-12",
        "foundation-13",
        "foundation-14",
    ):
        ((FOUNDATION_V10_V14,), "Foundation v10-v14"),
    (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ):
        ((OPENCFD_SERIES,), "OpenCFD v2106-v2606"),
}

# (model, checkouts, container, selector, description, note)
_MODELS = (
    ("Arrhenius", (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "ArrheniusCoeffs", "transportModel",
     (
         "Arrhenius type of dependency on a given scalar field name. Most likely "
         "temperature. The expression is as follow:"
     ),
     ""),
    ("BirdCarreau", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "BirdCarreauCoeffs", "transportModel",
     "An incompressible Bird-Carreau non-Newtonian viscosity model.",
     ""),
    ("Casson", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "CassonCoeffs", "transportModel",
     "An incompressible Casson non-Newtonian viscosity model.",
     (
         "Reference: Casson, N. (1959). Rheology of disperse systems. In Proceedings "
         "of a Conference Organized by the British Society of Rheology. Pergamon "
         "Press, New York. Fournier, R. L. (2011). Basic transport phenomena in "
         "biomedical engineering. CRC Press."
     )),
    ("CrossPowerLaw", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "CrossPowerLawCoeffs", "transportModel",
     "An incompressible Cross-Power law non-Newtonian viscosity model.",
     ""),
    ("HerschelBulkley", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "HerschelBulkleyCoeffs", "transportModel",
     "Herschel-Bulkley non-Newtonian viscosity model.",
     ""),
    ("Newtonian", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "", "transportModel",
     "An incompressible Newtonian viscosity model.",
     ""),
    ("constant", (
        "foundation-10",
        "foundation-11",
        "foundation-12",
        "foundation-13",
        "foundation-14",
    ), "", "viscosityModel",
     "A uniform constant Newtonian viscosity model.",
     ""),
    ("powerLaw", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "powerLawCoeffs", "transportModel",
     "Standard power-law non-Newtonian viscosity model.",
     ""),
    ("strainRateFunction", (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    ), "strainRateFunctionCoeffs", "transportModel",
     "Run-time selected strain-rate function non-Newtonian viscosity model.",
     ""),
)

# {model: {coefficient: (doc, note)}} — upstream's own words.
_COEFF_PROSE: dict[str, dict[str, tuple[str, str]]] = {
}

# (model, coefficient, source, ((raw, checkouts), ...), present_in)
_COEFFS = (
    ("Arrhenius", "Talpha", "Arrhenius.C", (
        (None, (
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Arrhenius", "alpha", "Arrhenius.C", (
        (None, (
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Arrhenius", "field", "Arrhenius.C", (
        ("\"T\"", (
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("BirdCarreau", "a", "BirdCarreau.C", (
        ("2", (
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("BirdCarreau", "k", "BirdCarreau.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("BirdCarreau", "n", "BirdCarreau.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("BirdCarreau", "nu0", "BirdCarreau.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("BirdCarreau", "nuInf", "BirdCarreau.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Casson", "m", "Casson.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Casson", "nuMax", "Casson.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Casson", "nuMax_", "Casson.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
    )),
    ("Casson", "nuMin", "Casson.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Casson", "nuMin_", "Casson.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
    )),
    ("Casson", "tau0", "Casson.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("CrossPowerLaw", "m", "CrossPowerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("CrossPowerLaw", "n", "CrossPowerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("CrossPowerLaw", "nu0", "CrossPowerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("CrossPowerLaw", "nuInf", "CrossPowerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("HerschelBulkley", "k", "HerschelBulkley.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("HerschelBulkley", "n", "HerschelBulkley.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("HerschelBulkley", "nu0", "HerschelBulkley.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("HerschelBulkley", "tau0", "HerschelBulkley.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("Newtonian", "nu", "Newtonian.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("constant", "nu", "constantViscosityModel.C", (
        (None, (
            "foundation-10",
            "foundation-11",
            "foundation-12",
            "foundation-13",
            "foundation-14",
        )),
    ), (
        "foundation-10",
        "foundation-11",
        "foundation-12",
        "foundation-13",
        "foundation-14",
    )),
    ("powerLaw", "k", "powerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("powerLaw", "n", "powerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("powerLaw", "nuMax", "powerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("powerLaw", "nuMin", "powerLaw.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
    ("strainRateFunction", "function", "strainRateFunction.C", (
        (None, (
            "foundation-7",
            "foundation-8",
            "foundation-9",
            "opencfd-v2106",
            "opencfd-v2112",
            "opencfd-v2206",
            "opencfd-v2212",
            "opencfd-v2306",
            "opencfd-v2312",
            "opencfd-v2406",
            "opencfd-v2412",
            "opencfd-v2506",
            "opencfd-v2512",
            "opencfd-v2606",
        )),
    ), (
        "foundation-7",
        "foundation-8",
        "foundation-9",
        "opencfd-v2106",
        "opencfd-v2112",
        "opencfd-v2206",
        "opencfd-v2212",
        "opencfd-v2306",
        "opencfd-v2312",
        "opencfd-v2406",
        "opencfd-v2412",
        "opencfd-v2506",
        "opencfd-v2512",
        "opencfd-v2606",
    )),
)


def _tags(checkouts):
    key = tuple(checkouts)
    if key in _TAGS:
        return _TAGS[key]
    consts, names = [], []
    for v in _ORDER:
        if v in key:
            c, n = _RELEASE[v]
            consts.append(c)
            names.append(n)
    return tuple(consts), ", ".join(names)


def _union(sets):
    return tuple(v for v in _ORDER if any(v in s for s in sets))


def _coeff_entry(model, name, src, groups, present, absent,
                 container, doc="", upstream_note=""):
    """One coefficient of one model.

    Every read in this family is either required (the source has no fallback)
    or defaulted through getOrDefault. `default` is stated only when there is
    exactly one value across the releases in this file; the choices carry the
    rest with their own version tags.
    """
    defaulted = [(raw, where) for raw, where in groups if raw is not None]
    required = not defaulted
    default = defaulted[0][0] if len(groups) == 1 and defaulted else ""
    where_txt = (f"the {container} sub-dictionary"
                 if container else "the dictionary itself")
    presence = f"Only present in {_tags(present)[1]}." if absent else ""
    return KeySchema(
        key=name,
        label=name,
        description=(
            (doc.rstrip(" .:") + ". " if doc else "")
            + f"{model} viscosity model coefficient, read in {src} from "
            f"{where_txt}."),
        supported_in=_tags(present)[0],
        default=default,
        required=required,
        note=" ".join(x for x in (upstream_note, presence) if x),
        choices=tuple(
            ChoiceItem(
                value=raw,
                description=f"Source default in {_tags(where)[1]}.",
                supported_in=_tags(where)[0],
            )
            for raw, where in defaulted),
    )


def _merged_plain(name, owners):
    """One flat entry for a key several models read.

    optionalSubDict lets a coefficient be written in the parent dictionary
    rather than inside <Model>Coeffs, so the flat spelling has to resolve. It
    names every owner; inside a model's own sub-dictionary that model's entry
    wins because FoDE resolves "<parent>.<key>" first.
    """
    models = sorted({o["model"] for o in owners})
    if len(models) == 1:
        return owners[0]["schema"]

    by_value = {}
    for o in owners:
        for raw, where in o["groups"]:
            if raw is None:
                continue
            e = by_value.setdefault(raw, {"models": [], "where": []})
            if o["model"] not in e["models"]:
                e["models"].append(o["model"])
            e["where"].append(where)

    choices = tuple(
        ChoiceItem(
            value=raw,
            description=(f"Default for {', '.join(sorted(e['models']))} "
                         f"in {_tags(_union(e['where']))[1]}."),
            supported_in=_tags(_union(e["where"]))[0],
        )
        for raw, e in by_value.items())

    return KeySchema(
        key=name,
        label=name,
        description=(
            f"Coefficient of {len(models)} viscosity models: "
            f"{', '.join(models)}. Read via optionalSubDict, so it may be "
            f"written directly in the parent dictionary — inside a "
            f"<model>Coeffs dictionary that model's own entry applies."),
        supported_in=_tags(_union([o["present"] for o in owners]))[0],
        required=not by_value,
        note=("No model that reads it supplies a default."
              if not by_value else
              f"The {len(models)} models that read it do not agree on a "
              f"default; each is listed below." if len(by_value) > 1 else ""),
        choices=choices,
    )


def build_schemas(target_file: str) -> dict[str, KeySchema]:
    """The KeySchema table for one dictionary file."""
    within = set(_TARGET_CHECKOUTS.get(target_file, ()))
    table: dict[str, KeySchema] = {}
    plain: dict[str, list] = {}
    selector_models: dict[str, list] = {}

    for model, all_checkouts, container, selector, desc, note in _MODELS:
        checkouts = tuple(v for v in all_checkouts if v in within)
        if not checkouts:
            continue
        if selector:
            selector_models.setdefault(selector, []).append(
                (model, checkouts, desc))
        mine = [c for c in _COEFFS
                if c[0] == model and any(v in within for v in c[4])]
        prose = _COEFF_PROSE.get(model, {})

        if container and mine:
            table[container] = KeySchema(
                key=container,
                label=model + " Coefficients",
                note=note,
                description=((desc.rstrip(" .:") + ". ") if desc else "") + (
                    f"Optional coefficient sub-dictionary for the {model} "
                    f"viscosity model. Read via optionalSubDict, so the "
                    f"coefficients below may also be placed directly in the "
                    f"parent dictionary. {len(mine)} coefficients covered by "
                    f"the foamlore store."),
                supported_in=_tags(checkouts)[0],
            )

        for _, name, src, groups, present_in in mine:
            present = tuple(v for v in present_in if v in within)
            absent = tuple(v for v in checkouts if v not in present_in)
            here = tuple((raw, tuple(v for v in where if v in within))
                         for raw, where in groups
                         if any(v in within for v in where))
            schema = _coeff_entry(model, name, src, here, present, absent,
                                  container, *prose.get(name, ("", "")))
            if container:
                table[container + "." + name] = schema
            plain.setdefault(name, []).append(
                {"model": model, "schema": schema,
                 "present": present, "groups": here})

    for name, owners in plain.items():
        table[name] = _merged_plain(name, owners)

    # The selector itself, measured from the base class's New .C rather than
    # declared here. It is the key a user actually writes, and Foundation
    # renamed it transportModel -> viscosityModel at v10.
    for key, entries in selector_models.items():
        table[key] = KeySchema(
            key=key,
            label="Viscosity model",
            description=(
                "Selects the viscosity model. Runtime-selected, so the valid "
                "values are exactly the models the release registers."),
            supported_in=_tags(_union([c for _, c, _ in entries]))[0],
            required=True,
            choices=tuple(
                ChoiceItem(
                    value=model,
                    description=one_line_choice(desc, model),
                    supported_in=_tags(checkouts)[0],
                )
                for model, checkouts, desc in sorted(entries)),
        )

    return table


def one_line_choice(desc, model):
    return desc if desc else f"The {model} viscosity model."

