# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_fode_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: DeardorffDiffStress.derived.json, EBRSM.derived.json, GEKO.derived.json, LRR.derived.json,
#   LaunderSharmaKE.derived.json, RNGkEpsilon.derived.json, SSG.derived.json,
#   Smagorinsky.derived.json, SpalartAllmaras.derived.json, SpalartAllmarasDDES.derived.json,
#   SpalartAllmarasDES.derived.json, SpalartAllmarasIDDES.derived.json, WALE.derived.json,
#   dynamicKEqn.derived.json, dynamicLagrangian.derived.json, kEpsilon.derived.json,
#   kEpsilonPhitF.derived.json, kEqn.derived.json, kOmega.derived.json, kOmega2006.derived.json,
#   kOmegaSST.derived.json, kOmegaSSTDDES.derived.json, kOmegaSSTDES.derived.json,
#   kOmegaSSTIDDES.derived.json, kOmegaSSTLM.derived.json, kOmegaSSTSAS.derived.json,
#   realizableKE.derived.json, sigma.derived.json, v2f.derived.json
# Source commits: foundation-8=a86b07b9, foundation-9=d87800e1, foundation-10=89f925dc,
#   foundation-11=9cbf94f3, foundation-12=0b487fc9, foundation-13=17489db
from __future__ import annotations

from schemas._base import KeySchema
from schemas._turbulence_coeffs import build_schemas

TARGET_FILE = "momentumTransport"

SCHEMAS: dict[str, KeySchema] = build_schemas(TARGET_FILE)
