# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_fode_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
# Inputs: kOmegaSST.derived.json, kEpsilon.derived.json, SpalartAllmaras.derived.json
# Source commits: foundation-13=17489db
from __future__ import annotations

from schemas._base import FOUNDATION_V13, ChoiceItem, KeySchema

TARGET_FILE = "momentumTransport"

SCHEMAS: dict[str, KeySchema] = {
    # ── SpalartAllmaras (RAS) ──────────────────────────────────────────
    "SpalartAllmarasCoeffs": KeySchema(
        key="SpalartAllmarasCoeffs",
        label="SpalartAllmaras Coefficients",
        description=(
            "Optional coefficient sub-dictionary for the SpalartAllmaras RAS model. "
            "Read via optionalSubDict, so the coefficients below may also be placed "
            "directly in the parent RAS dictionary. 8 coefficients covered by the "
            "foamlore store."
        ),
        supported_in=(FOUNDATION_V13,),
    ),
    "SpalartAllmarasCoeffs.Cb1": KeySchema(
        key="Cb1",
        label="Cb1",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.1355, read in "
            "the SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.1355",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cb1": KeySchema(
        key="Cb1",
        label="Cb1",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.1355, read in "
            "the SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.1355",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.Cb2": KeySchema(
        key="Cb2",
        label="Cb2",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.622, read in "
            "the SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.622",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cb2": KeySchema(
        key="Cb2",
        label="Cb2",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.622, read in "
            "the SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.622",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.Cs": KeySchema(
        key="Cs",
        label="Cs",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.3, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.3",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cs": KeySchema(
        key="Cs",
        label="Cs",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.3, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.3",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.Cv1": KeySchema(
        key="Cv1",
        label="Cv1",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 7.1, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="7.1",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cv1": KeySchema(
        key="Cv1",
        label="Cv1",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 7.1, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="7.1",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.Cw2": KeySchema(
        key="Cw2",
        label="Cw2",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.3, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.3",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cw2": KeySchema(
        key="Cw2",
        label="Cw2",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.3, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.3",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.Cw3": KeySchema(
        key="Cw3",
        label="Cw3",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 2.0, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="2.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cw3": KeySchema(
        key="Cw3",
        label="Cw3",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 2.0, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="2.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.kappa": KeySchema(
        key="kappa",
        label="kappa",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.41, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.41",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kappa": KeySchema(
        key="kappa",
        label="kappa",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.41, read in the "
            "SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.41",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "SpalartAllmarasCoeffs.sigmaNut": KeySchema(
        key="sigmaNut",
        label="sigmaNut",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.66666, read in "
            "the SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.66666",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "sigmaNut": KeySchema(
        key="sigmaNut",
        label="sigmaNut",
        description=(
            "SpalartAllmaras (RAS) model coefficient. Source default 0.66666, read in "
            "the SpalartAllmaras.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.66666",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    # ── kEpsilon (RAS) ─────────────────────────────────────────────────
    "kEpsilonCoeffs": KeySchema(
        key="kEpsilonCoeffs",
        label="kEpsilon Coefficients",
        description=(
            "Optional coefficient sub-dictionary for the kEpsilon RAS model. Read via "
            "optionalSubDict, so the coefficients below may also be placed directly in "
            "the parent RAS dictionary. 6 coefficients covered by the foamlore store."
        ),
        supported_in=(FOUNDATION_V13,),
    ),
    "kEpsilonCoeffs.C1": KeySchema(
        key="C1",
        label="C1",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.44, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.44",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "C1": KeySchema(
        key="C1",
        label="C1",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.44, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.44",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kEpsilonCoeffs.C2": KeySchema(
        key="C2",
        label="C2",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.92, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.92",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "C2": KeySchema(
        key="C2",
        label="C2",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.92, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.92",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kEpsilonCoeffs.C3": KeySchema(
        key="C3",
        label="C3",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 0, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "C3": KeySchema(
        key="C3",
        label="C3",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 0, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kEpsilonCoeffs.Cmu": KeySchema(
        key="Cmu",
        label="Cmu",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 0.09, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.09",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "Cmu": KeySchema(
        key="Cmu",
        label="Cmu",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 0.09, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.09",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kEpsilonCoeffs.sigmaEps": KeySchema(
        key="sigmaEps",
        label="sigmaEps",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.3, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.3",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "sigmaEps": KeySchema(
        key="sigmaEps",
        label="sigmaEps",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.3, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.3",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kEpsilonCoeffs.sigmak": KeySchema(
        key="sigmak",
        label="sigmak",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.0, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "sigmak": KeySchema(
        key="sigmak",
        label="sigmak",
        description=(
            "kEpsilon (RAS) model coefficient. Source default 1.0, read in the "
            "kEpsilon.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    # ── kOmegaSST (RAS) ────────────────────────────────────────────────
    "kOmegaSSTCoeffs": KeySchema(
        key="kOmegaSSTCoeffs",
        label="kOmegaSST Coefficients",
        description=(
            "Optional coefficient sub-dictionary for the kOmegaSST RAS model. Read via "
            "optionalSubDict, so the coefficients below may also be placed directly in "
            "the parent RAS dictionary. 13 coefficients covered by the foamlore store."
        ),
        supported_in=(FOUNDATION_V13,),
    ),
    "kOmegaSSTCoeffs.F3": KeySchema(
        key="F3",
        label="F3",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default false, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="false",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "F3": KeySchema(
        key="F3",
        label="F3",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default false, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="false",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.a1": KeySchema(
        key="a1",
        label="a1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.31, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.31",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "a1": KeySchema(
        key="a1",
        label="a1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.31, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.31",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.alphaK1": KeySchema(
        key="alphaK1",
        label="alphaK1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.85, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.85",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "alphaK1": KeySchema(
        key="alphaK1",
        label="alphaK1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.85, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.85",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.alphaK2": KeySchema(
        key="alphaK2",
        label="alphaK2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 1.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "alphaK2": KeySchema(
        key="alphaK2",
        label="alphaK2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 1.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.alphaOmega1": KeySchema(
        key="alphaOmega1",
        label="alphaOmega1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.5, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.5",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "alphaOmega1": KeySchema(
        key="alphaOmega1",
        label="alphaOmega1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.5, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.5",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.alphaOmega2": KeySchema(
        key="alphaOmega2",
        label="alphaOmega2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.856, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.856",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "alphaOmega2": KeySchema(
        key="alphaOmega2",
        label="alphaOmega2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.856, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.856",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.b1": KeySchema(
        key="b1",
        label="b1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 1.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "b1": KeySchema(
        key="b1",
        label="b1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 1.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="1.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.beta1": KeySchema(
        key="beta1",
        label="beta1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.075, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.075",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "beta1": KeySchema(
        key="beta1",
        label="beta1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.075, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.075",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.beta2": KeySchema(
        key="beta2",
        label="beta2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.0828, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.0828",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "beta2": KeySchema(
        key="beta2",
        label="beta2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.0828, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.0828",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.betaStar": KeySchema(
        key="betaStar",
        label="betaStar",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.09, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.09",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "betaStar": KeySchema(
        key="betaStar",
        label="betaStar",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.09, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.09",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.c1": KeySchema(
        key="c1",
        label="c1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 10.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="10.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "c1": KeySchema(
        key="c1",
        label="c1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 10.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="10.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.gamma1": KeySchema(
        key="gamma1",
        label="gamma1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 5.0/9.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="5.0/9.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "gamma1": KeySchema(
        key="gamma1",
        label="gamma1",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 5.0/9.0, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="5.0/9.0",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "kOmegaSSTCoeffs.gamma2": KeySchema(
        key="gamma2",
        label="gamma2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.44, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.44",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
    "gamma2": KeySchema(
        key="gamma2",
        label="gamma2",
        description=(
            "kOmegaSST (RAS) model coefficient. Source default 0.44, read in the "
            "kOmegaSSTBase.C constructor."
        ),
        supported_in=(FOUNDATION_V13,),
        choices=(
            ChoiceItem(
                value="0.44",
                description="Source default in Foundation v13.",
                supported_in=(FOUNDATION_V13,),
            ),
        ),
    ),
}
