# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_transport_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: Arrhenius.derived.json, BirdCarreau.derived.json, Casson.derived.json,
#   CrossPowerLaw.derived.json, HerschelBulkley.derived.json, Newtonian.derived.json,
#   constant.derived.json, powerLaw.derived.json, strainRateFunction.derived.json
# Source commits: foundation-10=89f925d, foundation-11=9cbf94f, foundation-12=0b487fc,
#   foundation-13=17489db, foundation-14=c046c72
from __future__ import annotations

from schemas._base import KeySchema
from schemas._transport import build_schemas

TARGET_FILE = "physicalProperties"

SCHEMAS: dict[str, KeySchema] = build_schemas(TARGET_FILE)
