# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_transport_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: Arrhenius.derived.json, BirdCarreau.derived.json, Casson.derived.json,
#   CrossPowerLaw.derived.json, HerschelBulkley.derived.json, Newtonian.derived.json,
#   constant.derived.json, powerLaw.derived.json, strainRateFunction.derived.json
# Source commits: opencfd-v2106=c15bfde, opencfd-v2112=14aeaf8, opencfd-v2206=76d719d,
#   opencfd-v2212=6690815, opencfd-v2306=a6e826b, opencfd-v2312=1d8f0d5, opencfd-v2406=630d60d,
#   opencfd-v2412=d394908, opencfd-v2506=615aae6, opencfd-v2512=87ed40d, opencfd-v2606=481094f,
#   foundation-7=6334942, foundation-8=a86b07b, foundation-9=d87800e
from __future__ import annotations

from schemas._base import KeySchema
from schemas._transport import build_schemas

TARGET_FILE = "transportProperties"

SCHEMAS: dict[str, KeySchema] = build_schemas(TARGET_FILE)
