# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Shinji NAKAGAWA
#
# GENERATED by foamlore facts/tools/generate_fode_schemas.py
# from the quote-verified fact store — NEVER edit by hand;
# regenerate after re-deriving.
#
# Descriptions and notes below quote documentation from the
# OpenFOAM source, which is Copyright (C) the OpenFOAM
# Foundation, OpenCFD Ltd, Upstream CFD GmbH and Keysight
# Technologies, licensed GPL-3.0-or-later. Per-file credits
# and the exact lines quoted are in THIRD-PARTY.md.
# Inputs: DeardorffDiffStress.derived.json, EBRSM.derived.json, GEKO.derived.json, LRR.derived.json,
#   LaunderSharmaKE.derived.json, RNGkEpsilon.derived.json, SSG.derived.json,
#   Smagorinsky.derived.json, SpalartAllmaras.derived.json, SpalartAllmarasDDES.derived.json,
#   SpalartAllmarasDES.derived.json, SpalartAllmarasIDDES.derived.json, WALE.derived.json,
#   dynamicKEqn.derived.json, dynamicLagrangian.derived.json, kEpsilon.derived.json,
#   kEpsilonPhitF.derived.json, kEqn.derived.json, kOmega.derived.json, kOmega2006.derived.json,
#   kOmegaSST.derived.json, kOmegaSSTDDES.derived.json, kOmegaSSTDES.derived.json,
#   kOmegaSSTIDDES.derived.json, kOmegaSSTLM.derived.json, kOmegaSSTSAS.derived.json,
#   realizableKE.derived.json, sigma.derived.json, v2f.derived.json
# Source commits: foundation-7=6334942, opencfd-v2106=c15bfde3, opencfd-v2206=76d719d1,
#   opencfd-v2212=66908158, opencfd-v2306=a6e826bd, opencfd-v2312=1d8f0d55, opencfd-v2406=630d60de,
#   opencfd-v2412=d3949086, opencfd-v2506=615aae61, opencfd-v2512=87ed40d, opencfd-v2606=481094f
from __future__ import annotations

from schemas._base import KeySchema
from schemas._turbulence_coeffs import build_schemas

TARGET_FILE = "turbulenceProperties"

SCHEMAS: dict[str, KeySchema] = build_schemas(TARGET_FILE)
